name: couple_space
description: "情侣共享空间：重笔记、轻日历的点对点情侣共享笔记 App。"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  cryptography: ^2.9.0
  drift: ^2.35.1
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image: ^4.10.1
  image_picker: ^1.2.3
  intl: ^0.20.3
  multicast_dns: ^0.3.3+1
  path_provider: ^2.1.6
  qr_flutter: ^4.1.0
  sqlite3_flutter_libs: ^0.6.0+eol
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.35.1
  build_runner: ^2.16.1

flutter:
  uses-material-design: true
